import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import { cn } from '@/lib/utils'
import "./globals.css";
import Link from "next/link";
import Image from 'next/image'
import * as React from "react";
import './layout.css'
import TwitterPic from '../../public/twitter@2x.png'
import TgPic from '../../public/tg@2x.png';
import EmailPic from '../../public/email@2x.png'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Cyber Leap Userinterface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={cn(
            "min-h-screen bg-background font-sans antialiased bg-gray",
            fontSans.variable
        )}
    >
    <header
        className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container-my flex h-14 max-w-screen-2xl items-center" style={{'gap': '24px'}}>
            <div className="logospace">
                <img
                    className="label_2"
                    src={"https://lanhu.oss-cn-beijing.aliyuncs.com/SketchPng80d9894646f196c38188762374123b34a4ce34d32af69d03bf10c2f01ef37de0"}
                  />
                  Hash Space
              </div>
              <Link href="/" legacyBehavior passHref>
                  首页
              </Link>
              <Link href="/cloudCount" legacyBehavior passHref>
                  云算力
              </Link>
              <Link href="/login" legacyBehavior passHref>
                  常见问题
              </Link>
              <Link href="/login" legacyBehavior passHref>
                  计算器
              </Link>
              <Link href="/login" legacyBehavior passHref>
                  关于
              </Link>

          </div>
      </header>
      {children}
      <div className="footer-cus">
          <div className="footer-container">
              <div className="logospace">
                  <img
                      className="label_2"
                      src={"https://lanhu.oss-cn-beijing.aliyuncs.com/SketchPng80d9894646f196c38188762374123b34a4ce34d32af69d03bf10c2f01ef37de0"}
                  />
                  Hash Space
              </div>
              <div>服务协议</div>
              <div>隐私政策</div>
              <div>免责声明</div>
              <div className='pic-row'>
                  <Image src={TwitterPic}
                         width={20}
                         height={20}
                         alt="twitter"
                  />
                  <Image src={TgPic}
                         width={20}
                         height={20}
                         alt="twitter"
                  />
                  <Image src={EmailPic}
                         width={20}
                         height={20}
                         alt="twitter"
                  />
              </div>
          </div>
          <div className="footer-info">© 2024 Hashspce. All</div>
      </div>
      </body>
    </html>
  );
}
